GET http://localhost:5284/games

###
GET http://localhost:5284/games/4

###
POST  http://localhost:5284/games
Content-Type: application/json 

{
    "name": "Street Fighter I",
    "genreId": 1,
    "price": 9.99,
    "releaseDate": "1991-11-08"
}

###
PUT http://localhost:5284/games/1
Content-Type: application/json

{
    "name": "Street Fighter III",
    "genre": "Fighting",
    "price": 20.99,
    "releaseDate": "1995-07-15"
}

###
DELETE http://localhost:5284/games/2